var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_MULTIPLIER = "x";
var TEXT_SCORE = "SCORE";
var TEXT_LEVEL_SCORE = "LEVEL SCORE";
var TEXT_TOTAL = "TOTAL SCORE";
var TEXT_GOAL = "GOAL!";
var TEXT_ARE_SURE = "LEAVE THE GAME?";
var TEXT_CONFIRM_DELETE = "THIS WILL DELETE YOUR SAVED PROGRESS.\nARE YOU SURE?";//"ALL SAVING WILL BE DELETED! ARE YOU SURE?";
var TEXT_CONFIRM_DELETE_MATCHES = "DO YOU WANT TO REDO ALL THE MATCHES?";//"ALL SAVING WILL BE DELETED! ARE YOU SURE?";
var TEXT_SAVED = "SAVED!";
var TEXT_MISSED = "MISS!";
var TEXT_MATCHPOINT = "MATCH POINT";
var TEXT_HELP = "SWIPE TO KICK THE BALL";
var TEXT_HELP_KEEPER = "TAP THE SCREEN TO LET THE OPPONENT KICK";
var TEXT_WIN = "YOU WON";
var TEXT_LOSE = "YOU LOSE";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";
var TEXT_VS = "VS";
var TEXT_MATCH = "MATCH";
var TEXT_SELECT_TEAM = "SELECT YOUR TEAM";
var TEXT_MATCHES = "MATCHES";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT LOCAL STORAGE. IF YOU'RE USING SAFARI, IT MAY BE RELATED TO PRIVATE BROWSING. AS A RESULT, SOME INFO MAY NOT BE SAVED OR SOME FEATURES MAY NOT BE AVAILABLE.";

var TEXT_PLAYER = "PLAYER";
var TEXT_CPU = "CPU";
var TEXT_EXTRA = "EXTRA";

var TEXT_TEAM = new Array();
TEXT_TEAM[0] = "RUSSIA";
TEXT_TEAM[1] = "JAPAN";
TEXT_TEAM[2] = "IRAN";
TEXT_TEAM[3] = "BRAZIL";
TEXT_TEAM[4] = "MEXICO";
TEXT_TEAM[5] = "USA";
TEXT_TEAM[6] = "SOUTH KOREA";
TEXT_TEAM[7] = "SAUDI ARABIA";
TEXT_TEAM[8] = "GERMANY";
TEXT_TEAM[9] = "ENGLAND";
TEXT_TEAM[10] = "SPAIN";
TEXT_TEAM[11] = "NIGERIA";
TEXT_TEAM[12] = "COSTA RICA";
TEXT_TEAM[13] = "POLAND";
TEXT_TEAM[14] = "EGYPT";
TEXT_TEAM[15] = "SERBIA";
TEXT_TEAM[16] = "CANADA";
TEXT_TEAM[17] = "FRANCE";
TEXT_TEAM[18] = "PORTUGAL";
TEXT_TEAM[19] = "URUGUAY";
TEXT_TEAM[20] = "ARGENTINA";
TEXT_TEAM[21] = "COLOMBIA";
TEXT_TEAM[22] = "ITALY";
TEXT_TEAM[23] = "SENEGAL";
TEXT_TEAM[24] = "MOROCCO";
TEXT_TEAM[25] = "TUNISIA";
TEXT_TEAM[26] = "SWITZERLAND";
TEXT_TEAM[27] = "CROATIA";
TEXT_TEAM[28] = "SWEDEN";
TEXT_TEAM[29] = "DENMARK";
TEXT_TEAM[30] = "AUSTRALIA";
TEXT_TEAM[31] = "PERU";

///////////// GAME MULTIPLAYER TEXT
var TEXT_NETWORK_CONNECTING = "CONNECTING...";
var TEXT_WAIT_OPPONENT = "WAITING FOR OPPONENT...";
var TEXT_OPPONENT_LEFT = "OPPONENT LEFT!";
var TEXT_PLAYER_DISCONNECTED = "YOU LEFT!";
var TEXT_REMATCH = "do you want the re-match?";
var TEXT_DISCONNECTED_FROM_SERVER = "DISCONNECTED FROM SERVER";
var TEXT_WAITING_FOR_OPPONENT = "WAITING FOR OPPONENT...";
var TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "OPPONENT WANTS TO PLAY AGAIN";
var TEXT_NETWORK_OFFLINE = "NETWORK OFFLINE";
var TEXT_RETURN_TO_HOME = "RETURN TO HOME";

///////////// LOGIN ROOM SYSTEM TEXT
var TEXT_WRONG_PASSWORD = "Wrong Password!";
var TEXT_ROOM_IS_FULL = "Room is full!";
var TEXT_FIND_OPPONENT = "FINDING OPPONENT...";
var TEXT_CONNECT_TO_LOBBY = "Connect to lobby...";
var TEXT_MATCH_FOUND = "Match found!";
var TEXT_ROOM_DOESNT_EXIST = "Room doesn't exist!";
var TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "waiting for opponent to join game: ";

///////////// NEW TEXT
var TEXT_WAIT_STRIKER = "YOUR OPPONENT IS KICKING";
var TEXT_GET_READY = "GET READY!";
var TEXT_WAIT_GOALKEEPER = "GOALKEEPER GETTING READY...";
var TEXT_GET_A_BONUS_SHOT = "GET A BONUS SHOT";
var TEXT_PLAYER_WAIT_TO_CALCULATE = "WAITING FOR OPPONENT\n TO CALCULATE THEIR SCORE";
var TEXT_QUIZ_TIMEOUT = "TIME'S UP";
var TEXT_WRONG_ANSWER = "INCORRECT";
var TEXT_CORRECT_ANSWER = "CORRECT!";
var TEXT_BONUS_SHOT = "BONUS SHOT";
var TEXT_PLAYER_TURN = "%s'S TURN";
var TEXT_CPU = "COMPUTER";
var TEXT_OPPONENT_BONUS_QUESTION = "OPPONENT'S BONUS SHOT QUESTION";
var TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "Opponent wants to play again";

/////////////SOCIAL TEXT
var TEXT_XP = "%s / %s XP";
var TEXT_XP_MAX = "MAX";
var TEXT_ACHIEVEMENTS = "TROPHIES";
var TEXT_STATS = "YOUR STATS";

var TEXT_LIST_ACHIEVEMENTS = new Array();
TEXT_LIST_ACHIEVEMENTS[ACHI_BRONZE_BOOT] = ["Bronze Boot","Score 50 goals"];
TEXT_LIST_ACHIEVEMENTS[ACHI_SILVER_BOOT] = ["Silver Boot","Score 250 goals"];
TEXT_LIST_ACHIEVEMENTS[ACHI_GOLDEN_BOOT] = ["Golden Boot","Score 1000 goals"];
TEXT_LIST_ACHIEVEMENTS[ACHI_MATHKICKER] = ["Mathkicker","Answer 25 math problems correctly"];
TEXT_LIST_ACHIEVEMENTS[ACHI_MATHOFTHEMATCH] = ["Math of the Match","Answer 100 math problems correctly"];
TEXT_LIST_ACHIEVEMENTS[ACHI_MATHLEGEND] = ["Math Legend ","Answer 500 math problems correctly"];
TEXT_LIST_ACHIEVEMENTS[ACHI_BRONZE_GLOVE] = ["Bronze Glove","Save 25 goals"];
TEXT_LIST_ACHIEVEMENTS[ACHI_SILVER_GLOVE] = ["Silver Glove","Save 100 goals"];
TEXT_LIST_ACHIEVEMENTS[ACHI_GOLDEN_GLOVE] = ["Golden Glove","Save 500 goals"];
TEXT_LIST_ACHIEVEMENTS[ACHI_HAT_TRICK] = ["Hat Trick","Score 3 Goals In A Row"];
TEXT_LIST_ACHIEVEMENTS[ACHI_GOAL_MACHINE] = ["Goal Machine","Score 5 or more goals in 3 matches"];
TEXT_LIST_ACHIEVEMENTS[ACHI_GOAL_PHENOM] = ["Goal Phenom","Score 5 or more goals in 15 matches"];
TEXT_LIST_ACHIEVEMENTS[ACHI_GOAL_LEGEND] = ["Goal Legend","Score 5 or more goals in 50 matches"];
TEXT_LIST_ACHIEVEMENTS[ACHI_THE_FIRST] = ["The First","Win Your First Game"];
TEXT_LIST_ACHIEVEMENTS[ACHI_WORLD_CHAMPION] = ["World Champion","Beat Computer in Match 10"];

var TEXT_STATS_LABEL_0 = "Overall";
var TEXT_STATS_LABEL_1 = "Kicker";
var TEXT_STATS_LABEL_2 = "Keeper";
var TEXT_STATS_LABEL_3 = "Math Accuracy";

var TEXT_STATS0_GAMESLABEL = "Games";
var TEXT_STATS0_LABELLX = "Won";
var TEXT_STATS0_LABELRX = "Lost";
var TEXT_STATS0_FAVCOUNTRYLABEL = "Favorite Country";

var TEXT_STATS1_GOALSCORED = "GOALS SCORED";
var TEXT_STATS1_PERFECTGAMES = "PERFECT GAMES";
var TEXT_STATS1_EVERYSHOTS = "Scored every shot";
var TEXT_STATS1_SHOTS_TAKEN = "%s SHOTS TAKEN";
var TEXT_TBD = "T.B.D.";
var TEXT_STATS1_MISSES = "Misses";
var TEXT_STATS1_SAVES = "Saves";
var TEXT_STATS1_GOALS = "Goals";
var TEXT_PERCENT = "%";
var TEXT_HOT_ZONES = "HOT ZONES";
var TEXT_NO_SHOTS = "No Shots";
var TEXT_STATS1_HOT_ZONES_DESC = "Each number indicates the percentage of your shots that scored";
var TEXT_STATS2_SHOTSSAVED = "SHOTS SAVED";
var TEXT_STATS2_SHUTOUTS = "SHUTOUTS";
var TEXT_STATS2_SAVEPERCENTAGE = "SAVE PERCENTAGE";
var TEXT_STATS2_HOT_ZONES_DESC = "Each number indicates the percentage of shots you saved";
var TEXT_STATS3_ACCURACY = "ACCURACY";
var TEXT_STATS3_ADDITION = "Addition";
var TEXT_STATS3_SUBTRACTION = "Subtraction";
var TEXT_STATS3_MULTIPLICATION = "Multiplication";
var TEXT_STATS3_DIVISION = "Division";
var TEXT_STATS3_TOTAL = "TOTAL";

var TEXT_SUMMARY_TITLE = "XP EARNED";
var TEXT_SUMMARY_WON = "Match Won";
var TEXT_SUMMARY_LOSS = "Match Loss";
var TEXT_SUMMARY_GOALS_SCORED = "Goals Scored";
var TEXT_SUMMARY_GOALS_SAVED = "Goals Saved";
var TEXT_SUMMARY_SHUTOUT = "Shutout";
var TEXT_SUMMARY_TROPHIES = "Trophies";
var TEXT_SUMMARY_TOTAL = "Total";


///OUT TEXT
var TEXT_SYS_UPDATE = "update";
var TEXT_SYS_CREATEMATCH = "create match";
var TEXT_SYS_OK = "ok";
var TEXT_SYS_BACK = "back";
var TEXT_SYS_TYPEROOMPASS = "Type Room Password";
var TEXT_SYS_NAMEROOM = "Name Room";
var TEXT_SYS_DEFAULTROOMNAME = "%s's room";
var TEXT_SYS_INFOPASS = "If you don\'t set a password this room will be public.";
var TEXT_SYS_CREATEROOM = "Create Room";
var TEXT_SYS_CREATE = "create";
var TEXT_SYS_LOADING = "Loading...";


var TEXT_SYS_MATCH_LIST = "Join a Match:";
var TEXT_SYS_QUICKMATCH = "play random opponent";
var TEXT_SYS_PASSWORD = "Password (optional)";
var TEXT_SYS_PLAY_OFFLINE = "PLAY OFFLINE";
var TEXT_SYS_NO_CONNECTION = "NO CONNECTION<br/>(Connect to find someone to play online)";



function refreshLanguage(){
    switch(s_iCurLang){
        case LANG_IT:{
            TEXT_PRELOADER_CONTINUE = "GIOCA";
            TEXT_MULTIPLIER = "x";
            TEXT_SCORE = "PUNTI";
            TEXT_LEVEL_SCORE = "PUNTI LIVELLO";
            TEXT_TOTAL = "PUNTEGGIO TOTALE";
            TEXT_GOAL = "GOAL!";
            TEXT_ARE_SURE = "LASCIARE IL GIOCO?";
            TEXT_CONFIRM_DELETE = "QUESTO CANCELLERA' TUTTI I TUOI PROGRESSI SALVATI.\n SEI SICURO?"; //TUTTI I DATI SALVATI SARANNO CANCELLATI! SEI SICURO?";
            TEXT_CONFIRM_DELETE_MATCHES = "VUOI RIGIOCARE TUTTE LE PARTITE?";//"TUTTI I DATI SALVATI SARANNO CANCELLATI! SEI SICURO?";
            TEXT_SAVED = "PARATA!";
            TEXT_MISSED = "MANCATA!";
            TEXT_MATCHPOINT = "MATCH POINT";
            TEXT_HELP = "FAI UNO SWIPE PER CALCIARE LA PALLA";
            TEXT_HELP_KEEPER = "TOCCA LO SCHERMO PER FAR TIRARE L'AVVERSARIO";
            TEXT_WIN = "HAI VINTO!";
            TEXT_LOSE = "HAI PERSO!";
            TEXT_CREDITS_DEVELOPED = "CREATO DA";
            TEXT_VS = "VS";
            TEXT_MATCH = "PARTITA";
            TEXT_SELECT_TEAM = "SCEGLI LA TUA SQUADRA";
            TEXT_MATCHES = "PARTITE";
            TEXT_ERR_LS = "IL TUO WEB BROWSER NON SUPPORTA IL SALVATAGGIO IN LOCALE. SE STAI USANDO SAFARI, QUESTO PUO' ESSERE COLLEGATO ALLA NAVIGAZIONE IN INCOGNITO. DI CONSEGUENZA, QUALCHE INFO PUO' NON ESSERE SALVATA O QUALCHE FUNZIONALITA' PUO' NON ESSERE DISPONIBILE.";
            TEXT_PLAYER = "GIOCATORE";
            TEXT_CPU = "CPU";
            TEXT_EXTRA = "EXTRA";

            TEXT_TEAM [0] = "RUSSIA";
            TEXT_TEAM [1] = "GIAPPONE";
            TEXT_TEAM [2] = "IRAN";
            TEXT_TEAM [3] = "BRASILE";
            TEXT_TEAM [4] = "MESSICO";
            TEXT_TEAM [5] = "USA";
            TEXT_TEAM [6] = "COREA DEL SUD";
            TEXT_TEAM [7] = "ARABIA SAUDITA";
            TEXT_TEAM [8] = "GERMANIA";
            TEXT_TEAM [9] = "INGHILTERRA";
            TEXT_TEAM [10] = "SPAGNA";
            TEXT_TEAM [11] = "NIGERIA";
            TEXT_TEAM [12] = "COSTA RICA";
            TEXT_TEAM [13] = "POLONIA";
            TEXT_TEAM [14] = "EGITTO";
            TEXT_TEAM [15] = "SERBIA";
            TEXT_TEAM [16] = "CANADA";
            TEXT_TEAM [17] = "FRANCIA";
            TEXT_TEAM [18] = "PORTOGALLO";
            TEXT_TEAM [19] = "URUGUAY";
            TEXT_TEAM [20] = "ARGENTINA";
            TEXT_TEAM [21] = "COLOMBIA";
            TEXT_TEAM [22] = "ITALIA";
            TEXT_TEAM [23] = "SENEGAL";
            TEXT_TEAM [24] = "MAROCCO";
            TEXT_TEAM [25] = "TUNISIA";
            TEXT_TEAM [26] = "SVIZZERA";
            TEXT_TEAM [27] = "CROAZIA";
            TEXT_TEAM [28] = "SVEZIA";
            TEXT_TEAM [29] = "DANIMARCA";
            TEXT_TEAM [30] = "AUSTRALIA";
            TEXT_TEAM [31] = "PERÙ";
            TEXT_NETWORK_CONNECTING  = "IN CONNESSIONE...";
            TEXT_WAIT_OPPONENT = "IN ATTESA DELL'AVVERSARIO";
            TEXT_OPPONENT_LEFT = "L'AVVERSARIO HA ABBANDONATO LA PARTITA";
            TEXT_PLAYER_DISCONNECTED = "HAI ABBANDONATO LA PARTITA!";
            TEXT_REMATCH = "Vuoi la rivincita?";
            TEXT_DISCONNECTED_FROM_SERVER = "DISCONNESSO DAL SERVER";
            TEXT_WAITING_FOR_OPPONENT = "IN ATTESA DELL'AVVERSARIO";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "L'AVVERSARIO VUOLE GIOCARE DI NUOVO";
            TEXT_NETWORK_OFFLINE = "NETWORK OFFLINE";
            TEXT_RETURN_TO_HOME = "TORNA ALLA HOME";
            TEXT_WRONG_PASSWORD = "PASSWORD ERRATA";
            TEXT_ROOM_IS_FULL = "La stanza è piena!";
            TEXT_FIND_OPPONENT = "RICERCA AVVERSARIO";
            TEXT_CONNECT_TO_LOBBY = "Connettiti alla lobby...";
            TEXT_MATCH_FOUND = "Partita trovata!";
            TEXT_ROOM_DOESNT_EXIST = "La stanza non esiste!";
            TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "In attesa che un avversario si unisca al gioco:";

            TEXT_WAIT_STRIKER = "IL TUO AVVERSARIO STA TIRANDO";
            TEXT_GET_READY = "PREPARATI!";
            TEXT_WAIT_GOALKEEPER = "IL PORTIERE SI STA PREPARANDO...";
            TEXT_GET_A_BONUS_SHOT = "VINCI UN TIRO BONUS";
            TEXT_PLAYER_WAIT_TO_CALCULATE = "IN ATTESA DELL'AVVERSARIO PER CALCOLARE IL PUNTEGGIO";
            TEXT_QUIZ_TIMEOUT = "TEMPO SCADUTO!";
            TEXT_WRONG_ANSWER = "ERRATO";
            TEXT_CORRECT_ANSWER = "CORRETTO";
            TEXT_BONUS_SHOT = "TIRO BONUS";
            TEXT_PLAYER_TURN = "TURNO DI %S";
            TEXT_CPU = "COMPUTER";
            TEXT_OPPONENT_BONUS_QUESTION = "DOMANDA TIRO BONUS PER L'AVVERSARIO";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "L'avversario vuole giocare di nuovo";

            TEXT_XP = "%s / %s XP";
            TEXT_XP_MAX = "MAX";
            TEXT_ACHIEVEMENTS = "TROFEI";
            TEXT_STATS = "LE TUE STATISTICHE";

            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_BOOT] = ["Stivale di Bronzo", "Fai 50 goal"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_BOOT] = ["Stivale d'Argento", "Fai 250 goal"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_BOOT] = ["Stivale d'Oro", "Fai 1000 goal"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHKICKER] = ["Il calciatore Matematico", "Rispondi a 25 quesiti correttamente"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHOFTHEMATCH] = ["Il matematico delle Partite", "Rispondi a 100 quesiti correttamente"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHLEGEND] = ["Leggenda Matematica", "Rispondi a 500 quesiti correttamente"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_GLOVE] = ["Guanto di Bronzo", "Para 25 Goal"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_GLOVE] = ["Guanto d'Argento", "Para 100 Goal"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_GLOVE] = ["Guanto d'Oro", "Para 500 Goal"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_HAT_TRICK] = ["Tripletta", "Fai 3 Goal di Seguito"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_MACHINE] = ["Goal Machine", "Fai 5 o più goal in 3 partite"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_PHENOM] = ["Fenomeno", "Fai 5 o più goal in 15 partite"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_LEGEND] = ["Leggenda", "Fai 5 o più goal in 15 partite"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_THE_FIRST] = ["Primo", "Vinci la tua prima partita"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_WORLD_CHAMPION] = ["Campione del mondo", "Batti il Computer nella partita 10"];

            TEXT_STATS_LABEL_0 = "Generale";
            TEXT_STATS_LABEL_1 = "Calciatore";
            TEXT_STATS_LABEL_2 = "Portiere";
            TEXT_STATS_LABEL_3 = "Precisione Matematica";

            TEXT_STATS0_GAMESLABEL = "Partite";
            TEXT_STATS0_LABELLX = "Vittorie";
            TEXT_STATS0_LABELRX = "Sconfitte";
            TEXT_STATS0_FAVCOUNTRYLABEL = "Paese Favorito";

            TEXT_STATS1_GOALSCORED = "Goal Segnati";
            TEXT_STATS1_PERFECTGAMES = "Partite Perfette";
            TEXT_STATS1_EVERYSHOTS = "Fatti ad ogni Goal";
            TEXT_STATS1_SHOTS_TAKEN = "%s TIRI FATTI";
            TEXT_TBD = "n.d.";
            TEXT_STATS1_MISSES = "Perse";
            TEXT_STATS1_SAVES = "Parate";
            TEXT_STATS1_GOALS = "Goal";
            TEXT_PERCENT = "%";
            TEXT_HOT_ZONES = "ZONE HOT";
            TEXT_NO_SHOTS = "Nessun Tiro";
            TEXT_STATS1_HOT_ZONES_DESC = "Ogni numero indica la percentuale di tiri andati a buon fine";
            TEXT_STATS2_SHOTSSAVED = "TIRI PARATI";
            TEXT_STATS2_SHUTOUTS = "CAPPOTTI";
            TEXT_STATS2_SAVEPERCENTAGE = "PERCENTUALE DI PARATE";
            TEXT_STATS2_HOT_ZONES_DESC = "Ogni numero indica la percentuale dei tiri parati";
            TEXT_STATS3_ACCURACY = "PRECISIONE";
            TEXT_STATS3_ADDITION = "Addizione";
            TEXT_STATS3_SUBTRACTION = "Sottrazione";
            TEXT_STATS3_MULTIPLICATION = "Moltiplicazione";
            TEXT_STATS3_DIVISION = "Divisione";
            TEXT_STATS3_TOTAL = "TOTALE";

            TEXT_SUMMARY_TITLE = "XP GUADAGNATA";
            TEXT_SUMMARY_WON = "Vittorie";
            TEXT_SUMMARY_LOSS = "Sconfitte";
            TEXT_SUMMARY_GOALS_SCORED = "Goal Fatti";
            TEXT_SUMMARY_GOALS_SAVED = "Goal Parati";
            TEXT_SUMMARY_SHUTOUT = "Cappotto";
            TEXT_SUMMARY_TROPHIES = "Trofei";
            TEXT_SUMMARY_TOTAL = "Totale";  
            
            ///OUT TEXT
            TEXT_SYS_UPDATE = "aggiorna";
            TEXT_SYS_CREATEMATCH = "crea match";
            TEXT_SYS_OK = "ok";
            TEXT_SYS_BACK = "indietro";
            TEXT_SYS_TYPEROOMPASS = "Digita la password della stanza";
            TEXT_SYS_NAMEROOM = "Nome della Stanza";
            TEXT_SYS_DEFAULTROOMNAME = "Stanza di %s";
            TEXT_SYS_INFOPASS = "Se non imposti una password la stanza sarà pubblica";
            TEXT_SYS_CREATEROOM = "Crea una stanza";
            TEXT_SYS_CREATE = "crea";
            TEXT_SYS_LOADING = "Caricamento...";


            TEXT_SYS_MATCH_LIST = "Entra in una partita:";
            TEXT_SYS_QUICKMATCH = "Sfida un avversario random";
            TEXT_SYS_PASSWORD = "Password (opzionale)";
            TEXT_SYS_PLAY_OFFLINE = "GIOCA OFFLINE";
            TEXT_SYS_NO_CONNECTION = "NESSUNA CONNESSIONE <br/> (Connettiti per trovare qualcuno con cui giocare online)";
            
            break;  
        }
        case LANG_FR:{
            TEXT_PRELOADER_CONTINUE = "DÉMARRER";
            TEXT_MULTIPLIER = "x";
            TEXT_SCORE = "SCORE";
            TEXT_LEVEL_SCORE = "SCORE DU NIVEAU";
            TEXT_TOTAL = "SCORE TOTAL";
            TEXT_GOAL = "BUT !";
            TEXT_ARE_SURE = "QUITTER LE JEU ?";
            TEXT_CONFIRM_DELETE = "CECI EFFACERA TA PROGRESSION  SAUVEGARDÉE.\nES-TU CERTAIN ?";//"TOUT CE QUI A ÉTÉ SAUVEGARDÉ SERA EFFACÉ ! ES-TU CERTAIN ?";
            TEXT_CONFIRM_DELETE_MATCHES = "VEUX-TU REJOUER TOUTES LES PARTIES ? ";//"TOUT CE QUI A ÉTÉ SAUVEGARDÉ SERA EFFACÉ ! ES-TU CERTAIN ?";
            TEXT_SAVED = "ARRÊT RÉUSSI !";
            TEXT_MISSED = "TIR MANQUÉ !";
            TEXT_MATCHPOINT = "BUT DÉCISIF";
            TEXT_HELP = "FAITES GLISSER POUR TIRER";
            TEXT_HELP_KEEPER = "APPUYEZ SUR L’ÉCRAN POUR LAISSER L’ADVERSAIRE TIRER";
            TEXT_WIN = "TU AS GAGNÉ";
            TEXT_LOSE = "TU AS PERDU";
            TEXT_CREDITS_DEVELOPED = "DÉVELOPPÉ PAR";
            TEXT_VS = "VS";
            TEXT_MATCH = "PARTIE";
            TEXT_SELECT_TEAM = "CHOIX DE L’ÉQUIPE";
            TEXT_MATCHES = "PARTIES";
            TEXT_ERR_LS = "VOTRE NAVIGATEUR N’AUTORISE PAS LE STOCKAGE WEB LOCAL. SUR SAFARI, CELA PEUT ÊTRE DÛ À L’UTILISATION DU MODE DE NAVIGATION PRIVÉE. CERTAINES INFORMATIONS PEUVENT DONC NE PAS ÊTRE SAUVEGARDÉES OU CERTAINES FONCTIONNALITÉS RISQUENT D’ÊTRE INDISPONIBLES.";
            TEXT_PLAYER = "JOUEUR";
            TEXT_CPU = "IA";
            TEXT_EXTRA = "EXTRA";

            TEXT_TEAM [0] = "RUSSIE";
            TEXT_TEAM [1] = "JAPON";
            TEXT_TEAM [2] = "IRAN";
            TEXT_TEAM [3] = "BRÉSIL";
            TEXT_TEAM [4] = "MEXIQUE";
            TEXT_TEAM [5] = "ÉTATS-UNIS";
            TEXT_TEAM [6] = "CORÉE DU SUD";
            TEXT_TEAM [7] = "ARABIE SAOUDITE";
            TEXT_TEAM [8] = "ALLEMAGNE";
            TEXT_TEAM [9] = "ANGLETERRE";
            TEXT_TEAM [10] = "ESPAGNE";
            TEXT_TEAM [11] = "NIGÉRIA";
            TEXT_TEAM [12] = "COSTA RICA";
            TEXT_TEAM [13] = "POLOGNE";
            TEXT_TEAM [14] = "ÉGYPTE";
            TEXT_TEAM [15] = "SERBIE";
            TEXT_TEAM [16] = "CANADA";
            TEXT_TEAM [17] = "FRANCE";
            TEXT_TEAM [18] = "PORTUGAL";
            TEXT_TEAM [19] = "URUGUAY";
            TEXT_TEAM [20] = "ARGENTINE";
            TEXT_TEAM [21] = "COLOMBIE";
            TEXT_TEAM [22] = "ITALIE";
            TEXT_TEAM [23] = "SÉNÉGAL";
            TEXT_TEAM [24] = "MAROC";
            TEXT_TEAM [25] = "TUNISIE";
            TEXT_TEAM [26] = "SUISSE";
            TEXT_TEAM [27] = "CROATIE";
            TEXT_TEAM [28] = "LA SUÈDE";
            TEXT_TEAM [29] = "DANEMARK";
            TEXT_TEAM [30] = "AUSTRALIE";
            TEXT_TEAM [31] = "PÉROU";
            TEXT_NETWORK_CONNECTING  = "CONNEXION EN COURS...";
            TEXT_WAIT_OPPONENT = "EN ATTENTE D’UN ADVERSAIRE";
            TEXT_OPPONENT_LEFT = "TON ADVERSAIRE A QUITTÉ LA PARTIE";
            TEXT_PLAYER_DISCONNECTED = "TU AS QUITTÉ LA PARTIE !";
            TEXT_REMATCH = "Veux-tu une revanche ?";
            TEXT_DISCONNECTED_FROM_SERVER = "DÉCONNECTÉ DU SERVEUR";
            TEXT_WAITING_FOR_OPPONENT = "EN ATTENTE D’UN ADVERSAIRE";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "L’ADVERSAIRE VOUDRAIT REJOUER";
            TEXT_NETWORK_OFFLINE = "RÉSEAU HORS LIGNE";
            TEXT_RETURN_TO_HOME = "RETOUR À L’ACCUEIL";
            TEXT_WRONG_PASSWORD = "Mot de passe incorrect";
            TEXT_ROOM_IS_FULL = "La salle est complète !";
            TEXT_FIND_OPPONENT = "RECHERCHE D’ADVERSAIRE...";
            TEXT_CONNECT_TO_LOBBY = "Connexion au lobby ...";
            TEXT_MATCH_FOUND = "Partie trouvée !";
            TEXT_ROOM_DOESNT_EXIST = "La salle n’existe pas !";
            TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "En attente qu'un adversaire se joigne :";

            TEXT_WAIT_STRIKER = "VOTRE ADVERSAIRE VA TIRER";
            TEXT_GET_READY = "PRÉPARE-TOI !";
            TEXT_WAIT_GOALKEEPER = "LE GARDIEN SE PRÉPARE...";
            TEXT_GET_A_BONUS_SHOT = "OBTIENS UN TIR BONUS";
            TEXT_PLAYER_WAIT_TO_CALCULATE = "EN ATTENTE DU CALCUL\n DE L’ADVERSAIRE";
            TEXT_QUIZ_TIMEOUT = "TEMPS ÉCOULÉ";
            TEXT_WRONG_ANSWER = "MAUVAISE RÉPONSE";
            TEXT_CORRECT_ANSWER = "BONNE RÉPONSE";
            TEXT_BONUS_SHOT = "TIR BONUS";
            TEXT_PLAYER_TURN = "À %s DE JOUER";
            TEXT_CPU = "ORDINATEUR";
            TEXT_OPPONENT_BONUS_QUESTION = "QUESTION DU TIR BONUS DE L’ADVERSAIRE";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "L’adversaire voudrait refaire une partie";

            TEXT_XP = "%s / %s XP";
            TEXT_XP_MAX = "MAX";
            TEXT_ACHIEVEMENTS = "TROPHÉES";
            TEXT_STATS = "VOS STATS";

            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_BOOT ] = ["Chaussure de bronze","Marque 50 buts"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_BOOT] = ["Chaussure d’argent","Marque 250 buts"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_BOOT] = ["Chaussure d’or","Marque 1 000 buts"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHKICKER] = ["Mathématicien buteur","Résous 25 problèmes de math"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHOFTHEMATCH] = ["Mathématicien du match","Résous 100 problèmes de math"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHLEGEND] = ["Mathématicien légendaire","Résous 500 problèmes de math"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_GLOVE] = ["Gant de bronze","Arrête 25 tirs"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_GLOVE] = ["Gant d’argent","Arrête 100 tirs"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_GLOVE] = ["Gant d’or","Arrête 500 tirs"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_HAT_TRICK] = ["Coup du chapeau","Marque 3 tirs consécutifs"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_MACHINE] = ["Buteur expert","Marque au moins 5 buts au cours de 3 matchs différents"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_PHENOM] = ["Buteur phénoménal","Marque au moins 5 buts au cours de 15 matchs différents"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_LEGEND] = ["Buteur légendaire","Marque au moins 5 buts au cours de 50 matchs différents"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_THE_FIRST] = ["Premier trophée","Remporte ta 1re victoire"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_WORLD_CHAMPION] = ["Champion du monde","Remporte le match 10 contre l’ordinateur"];

            TEXT_STATS_LABEL_0 = "Global";
            TEXT_STATS_LABEL_1 = "Tireur";
            TEXT_STATS_LABEL_2 = "Gardien";
            TEXT_STATS_LABEL_3 = "Précision mathématique";

            TEXT_STATS0_GAMESLABEL = "Matchs";
            TEXT_STATS0_LABELLX = "Victoires";
            TEXT_STATS0_LABELRX = "Défaites";
            TEXT_STATS0_FAVCOUNTRYLABEL = "Nation favorite";

            TEXT_STATS1_GOALSCORED = "BUTS MARQUÉS";
            TEXT_STATS1_PERFECTGAMES = "PARTIES PARFAITES";
            TEXT_STATS1_EVERYSHOTS = "A marqué à chaque tir";
            TEXT_STATS1_SHOTS_TAKEN = "%s TIRS EFFECTUÉS";
            TEXT_TBD = "À déterminer";
            TEXT_STATS1_MISSES = "Échecs";
            TEXT_STATS1_SAVES = "Arrêts";
            TEXT_STATS1_GOALS = "Buts";
            TEXT_PERCENT = "%";
            TEXT_HOT_ZONES = "ZONES CHAUDES";
            TEXT_NO_SHOTS = "Aucun tir";
            TEXT_STATS1_HOT_ZONES_DESC = "Les nombres affichés indiquent le pourcentage de tirs marqués";
            TEXT_STATS2_SHOTSSAVED = "TIRS ARRÊTÉS";
            TEXT_STATS2_SHUTOUTS = "DÉFENSE PARFAITE";
            TEXT_STATS2_SAVEPERCENTAGE = "POURCENTAGE D’ARRÊTS";
            TEXT_STATS2_HOT_ZONES_DESC = "Les nombres affichés indiquent le pourcentage de tirs arrêtés";
            TEXT_STATS3_ACCURACY = "PRÉCISION";
            TEXT_STATS3_ADDITION = "Addition";
            TEXT_STATS3_SUBTRACTION = "Soustraction";
            TEXT_STATS3_MULTIPLICATION = "Multiplication";
            TEXT_STATS3_DIVISION = "Division";
            TEXT_STATS3_TOTAL = "TOTAL";

            TEXT_SUMMARY_TITLE = "XP GAGNÉE";
            TEXT_SUMMARY_WON = "Parties gagnées";
            TEXT_SUMMARY_LOSS = "Parties perdues";
            TEXT_SUMMARY_GOALS_SCORED = "Buts marqués";
            TEXT_SUMMARY_GOALS_SAVED = "Tirs arrêtés";
            TEXT_SUMMARY_SHUTOUT = "Défense parfaite";
            TEXT_SUMMARY_TROPHIES = "Trophées";
            TEXT_SUMMARY_TOTAL = "Total";
            
            ///OUT TEXT
            TEXT_SYS_UPDATE ="mise à jour"
            TEXT_SYS_CREATEMATCH = "créer une partie";
            TEXT_SYS_OK = "ok";
            TEXT_SYS_BACK = "retour";
            TEXT_SYS_TYPEROOMPASS = "Entre le mot de passe de la salle";
            TEXT_SYS_NAMEROOM = "Nom de la salle";
            TEXT_SYS_DEFAULTROOMNAME = "Salle créée par %s";
            TEXT_SYS_INFOPASS = "Si tu ne crées pas de mot de passe, cette salle sera publique.";
            TEXT_SYS_CREATEROOM = "Créer une salle";
            TEXT_SYS_CREATE = "créer";
            TEXT_SYS_LOADING = "Chargement...";


            TEXT_SYS_MATCH_LIST = "Se joindre à une partie";
            TEXT_SYS_QUICKMATCH = "Jouer contre un adversaire aléatoire";
            TEXT_SYS_PASSWORD = "Mot de passe (optionnel)";
            TEXT_SYS_PLAY_OFFLINE = "JOUER HORS LIGNE";
            TEXT_SYS_NO_CONNECTION = "PAS DE CONNEXION<br/>(Connecte-toi pour trouver des adversaires et jouer en ligne)";
            
            break;  
        }
        case LANG_ES:{
            TEXT_PRELOADER_CONTINUE = "INICIAR";
            TEXT_MULTIPLIER = "x";
            TEXT_SCORE = "PUNTOS";
            TEXT_LEVEL_SCORE = "PUNTOS DEL NIVEL";
            TEXT_TOTAL = "PUNTUACIÓN POR TIEMPO";
            TEXT_GOAL = "¡GOL!";
            TEXT_ARE_SURE = "¿SALIR DEL PARTIDO?";
            TEXT_CONFIRM_DELETE = "ESTO BORRARÁ TU PROGRESO GUARDADO.\n¿SEGURO?";//"¡SE PERDERÁ TODO LO GUARDADO! ¿SEGURO?";
            TEXT_CONFIRM_DELETE_MATCHES = "¿QUIERES REPETIR TODOS LOS PARTIDOS?";//"¡SE BORRARÁ TODO LO GUARDADO! ¿SEGURO?";
            TEXT_SAVED = "¡PARADO!";
            TEXT_MISSED = "¡FUERA!";
            TEXT_MATCHPOINT = "PUNTO DE PARTIDO";
            TEXT_HELP = "DESLIZA PARA GOLPEAR EL BALÓN";
            TEXT_HELP_KEEPER = "TOCA LA PANTALLA PARA QUE TU RIVAL PUEDA LANZAR";
            TEXT_WIN = "HAS GANADO";
            TEXT_LOSE = "HAS PERDIDO";
            TEXT_CREDITS_DEVELOPED = "DESARROLLADO POR";
            TEXT_VS = "CONTRA";
            TEXT_MATCH = "PARTIDO";
            TEXT_SELECT_TEAM = "ELIGE A TU EQUIPO";
            TEXT_MATCHES = "PARTIDOS";
            TEXT_ERR_LS = "TU NAVEGADOR NO ES COMPATIBLE CON EL ALMACENAMIENTO LOCAL. SI USAS SAFARI, PODRÍA ESTAR OCASIONADO POR LA NAVEGACIÓN PRIVADA. COMO RESULTADO, ALGUNA INFORMACIÓN PODRÍA NO GUARDARSE Y ALGUNAS FUNCIONES PUEDEN NO ESTAR DISPONIBLES.";
            TEXT_PLAYER = "JUGADOR";
            TEXT_CPU = "CPU";
            TEXT_EXTRA = "EXTRA";

            TEXT_TEAM [0] = "RUSIA";
            TEXT_TEAM [1] = "JAPÓN";
            TEXT_TEAM [2] = "IRÁN";
            TEXT_TEAM [3] = "BRASIL";
            TEXT_TEAM [4] = "MÉXICO";
            TEXT_TEAM [5] = "ESTADOS UNIDOS";
            TEXT_TEAM [6] = "COREA DEL SUR";
            TEXT_TEAM [7] = "ARABIA SAUDITA";
            TEXT_TEAM [8] = "ALEMANIA";
            TEXT_TEAM [9] = "INGLATERRA";
            TEXT_TEAM [10] = "ESPAÑA";
            TEXT_TEAM [11] = "NIGERIA";
            TEXT_TEAM [12] = "COSTA RICA";
            TEXT_TEAM [13] = "POLONIA";
            TEXT_TEAM [14] = "EGIPTO";
            TEXT_TEAM [15] = "SERBIA";
            TEXT_TEAM [16] = "CANADÁ";
            TEXT_TEAM [17] = "FRANCIA";
            TEXT_TEAM [18] = "PORTUGAL";
            TEXT_TEAM [19] = "URUGUAY";
            TEXT_TEAM [20] = "ARGENTINA";
            TEXT_TEAM [21] = "COLOMBIA";
            TEXT_TEAM [22] = "ITALIA";
            TEXT_TEAM [23] = "SENEGAL";
            TEXT_TEAM [24] = "MARRUECOS";
            TEXT_TEAM [25] = "TÚNEZ";
            TEXT_TEAM [26] = "SUIZA";
            TEXT_TEAM [27] = "CROACIA";
            TEXT_TEAM [28] = "SUECIA";
            TEXT_TEAM [29] = "DINAMARCA";
            TEXT_TEAM [30] = "AUSTRALIA";
            TEXT_TEAM [31] = "PERÚ";
            TEXT_NETWORK_CONNECTING  = "CONECTANDO...";
            TEXT_WAIT_OPPONENT = "ESPERANDO AL OPONENTE";
            TEXT_OPPONENT_LEFT = "EL OPONENTE HA SALIDO";
            TEXT_PLAYER_DISCONNECTED = "¡HAS SALIDO!";
            TEXT_REMATCH = "¿Quieres la revancha?";
            TEXT_DISCONNECTED_FROM_SERVER = "TE HAS DESCONECTADO DEL SERVIDOR";
            TEXT_WAITING_FOR_OPPONENT = "ESPERANDO AL OPONENTE";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "TU OPONENTE QUIERE JUGAR OTRA VEZ";
            TEXT_NETWORK_OFFLINE = "RED DESCONECTADA";
            TEXT_RETURN_TO_HOME = "VOLVER A CASA";
            TEXT_WRONG_PASSWORD = "Contraseña incorrecta";
            TEXT_ROOM_IS_FULL = "¡La sala está llena!";
            TEXT_FIND_OPPONENT = "buscando oponente...";
            TEXT_CONNECT_TO_LOBBY = "Conectando al lobby...";
            TEXT_MATCH_FOUND = "¡Partida encontrada!";
            TEXT_ROOM_DOESNT_EXIST = "¡La sala no existe!";
            TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "esperando a que se una un oponente:";

            TEXT_WAIT_STRIKER = "TU RIVAL ESTÁ GOLPEANDO EL BALÓN";
            TEXT_GET_READY = "¡PREPÁRATE!";
            TEXT_WAIT_GOALKEEPER = "PORTERO PREPARÁNDOSE...";
            TEXT_GET_A_BONUS_SHOT = "CONSIGUES UN TIRO EXTRA";
            TEXT_PLAYER_WAIT_TO_CALCULATE = "ESPERANDO A QUE EL OPONENTE\n CALCULE SU PUNTUACIÓN";
            TEXT_QUIZ_TIMEOUT = "TIEMPO";
            TEXT_WRONG_ANSWER = "INCORRECTO";
            TEXT_CORRECT_ANSWER = "CORRECTO";
            TEXT_BONUS_SHOT = "TIRO EXTRA";
            TEXT_PLAYER_TURN = "TURNO DE %s";
            TEXT_CPU = "ORDENADOR";
            TEXT_OPPONENT_BONUS_QUESTION = "PREGUNTA DE TIRO EXTRA DEL RIVAL";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "Tu oponente quiere jugar otra vez";

            TEXT_XP = "%s / %s XP";
            TEXT_XP_MAX = "MÁX.";
            TEXT_ACHIEVEMENTS = "TROFEOS";
            TEXT_STATS = "TUS ESTADÍSTICAS";

            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_BOOT ] = ["Bota de bronce","Marca 50 goles"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_BOOT] = ["Bota de plata","Marca 250 goles"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_BOOT] = ["Bota de oro","Marca 1000 goles"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHKICKER] = ["Re-Mates","Contesta correctamente a 25 problemas de matemáticas"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHOFTHEMATCH] = ["Tiempo de dos cuentas","Contesta correctamente a 100 problemas de matemáticas"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHLEGEND] = ["Tri-gol-ometría ","Contesta correctamente a 500 problemas de matemáticas"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_GLOVE] = ["Guantes de bronce","Para 25 goles"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_GLOVE] = ["Guantes de plata","Para 100 goles"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_GLOVE] = ["Guantes de oro","Para 500 goles"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_HAT_TRICK] = ["Triplete","Marca 3 goles seguidos"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_MACHINE] = ["Máquina de marcar","Marca 5 goles o más en 3 partidos"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_PHENOM] = ["Fenómeno","Marca 5 goles o más en 15 partidos"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_LEGEND] = ["Leyenda delantera","Marca 5 goles o más en 50 partidos"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_THE_FIRST] = ["Primero","Gana tu primer partido"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_WORLD_CHAMPION] = ["¡Oé, oé, oé!","Derrota al ordenador en el partido 10"];

            TEXT_STATS_LABEL_0 = "General";
            TEXT_STATS_LABEL_1 = "Tirador";
            TEXT_STATS_LABEL_2 = "Portero";
            TEXT_STATS_LABEL_3 = "Precisión matemática";

            TEXT_STATS0_GAMESLABEL = "Partidas";
            TEXT_STATS0_LABELLX = "Victorias";
            TEXT_STATS0_LABELRX = "Derrotas";
            TEXT_STATS0_FAVCOUNTRYLABEL = "País favorito";

            TEXT_STATS1_GOALSCORED = "GOLES MARCADOS";
            TEXT_STATS1_PERFECTGAMES = "PARTIDAS PERFECTAS";
            TEXT_STATS1_EVERYSHOTS = "Mete con todos los tiros";
            TEXT_STATS1_SHOTS_TAKEN = "%s TIROS DADOS";
            TEXT_TBD = "T.B.D.";
            TEXT_STATS1_MISSES = "Fallos";
            TEXT_STATS1_SAVES = "Paradas";
            TEXT_STATS1_GOALS = "Goles";
            TEXT_PERCENT = "%";
            TEXT_HOT_ZONES = "ZONAS CALIENTES";
            TEXT_NO_SHOTS = "Sin tiros";
            TEXT_STATS1_HOT_ZONES_DESC = "Cada número indica el porcentaje de tiros que han entrado.";
            TEXT_STATS2_SHOTSSAVED = "TIROS PARADOS";
            TEXT_STATS2_SHUTOUTS = "PARTIDAS INTACTAS";
            TEXT_STATS2_SAVEPERCENTAGE = "PORCENTAJE DE PARADAS";
            TEXT_STATS2_HOT_ZONES_DESC = "Cada número indica el porcentaje de tiros que has parado.";
            TEXT_STATS3_ACCURACY = "PRECISIÓN";
            TEXT_STATS3_ADDITION = "Suma";
            TEXT_STATS3_SUBTRACTION = "Resta";
            TEXT_STATS3_MULTIPLICATION = "Multiplicación";
            TEXT_STATS3_DIVISION = "División";
            TEXT_STATS3_TOTAL = "TOTAL";

            TEXT_SUMMARY_TITLE = "EXP GANADA";
            TEXT_SUMMARY_WON = "Partidos ganados";
            TEXT_SUMMARY_LOSS = "Partidos perdidos";
            TEXT_SUMMARY_GOALS_SCORED = "Goles marcados";
            TEXT_SUMMARY_GOALS_SAVED = "Goles parados";
            TEXT_SUMMARY_SHUTOUT = "Victoria intacta";
            TEXT_SUMMARY_TROPHIES = "Trofeos";
            TEXT_SUMMARY_TOTAL = "Total";
            
            TEXT_SYS_UPDATE ="actualizar"
            TEXT_SYS_CREATEMATCH = "CREAR PARTIDA";
            TEXT_SYS_OK = "Aceptar";
            TEXT_SYS_BACK = "ATRÁS";
            TEXT_SYS_TYPEROOMPASS = "ESCRIBE LA CONTRASEÑA DE LA SALA";
            TEXT_SYS_NAMEROOM = "Nombre de sala";
            TEXT_SYS_DEFAULTROOMNAME = "Sala de %s";
            TEXT_SYS_INFOPASS = "Esta sala será pública si no pones una contraseña.";
            TEXT_SYS_CREATEROOM = "CREAR SALA";
            TEXT_SYS_CREATE = "CREAR";
            TEXT_SYS_LOADING = "CARGANDO...";


            TEXT_SYS_MATCH_LIST = "Unirse a una partida:";
            TEXT_SYS_QUICKMATCH = "Jugar contra oponente aleatorio";
            TEXT_SYS_PASSWORD = "Contraseña (opcional)";
            TEXT_SYS_PLAY_OFFLINE = "JUGAR SIN CONEXIÓN";
            TEXT_SYS_NO_CONNECTION = "SIN CONEXIÓN<br/>(Conéctate para jugar en línea con alguien)";
            
            break;  
        }
        case LANG_PT:{
            TEXT_PRELOADER_CONTINUE = "INICIAR";
            TEXT_MULTIPLIER = "x";
            TEXT_SCORE = "PONTUAÇÃO";
            TEXT_LEVEL_SCORE = "PONTUAÇÃO DO NÍVEL";
            TEXT_TOTAL = "PONTUAÇÃO TOTAL";
            TEXT_GOAL = "GOLO!";
            TEXT_ARE_SURE = "SAIR DO JOGO?";
            TEXT_CONFIRM_DELETE = "VOCÊ PERDERÁ SEU PROGRESSO.\nTEM CERTEZA?";//"OS JOGOS SALVOS SERÃO EXCLUÍDOS! TEM CERTEZA?";
            TEXT_CONFIRM_DELETE_MATCHES = "REFAZER TODAS AS PARTIDAS?";//"OS JOGOS SALVOS SERÃO EXCLUÍDOS! TEM CERTEZA?";
            TEXT_SAVED = "DEFENDIDO!";
            TEXT_MISSED = "FALHADO!";
            TEXT_MATCHPOINT = "BOLA DO JOGO";
            TEXT_HELP = "DESLIZA PARA REMATAR";
            TEXT_HELP_KEEPER = "TOCA NO ECRÃ PARA O ADVERSÁRIO REMATAR";
            TEXT_WIN = "GANHASTE";
            TEXT_LOSE = "PERDESTE";
            TEXT_CREDITS_DEVELOPED = "DESENVOLVIDO POR";
            TEXT_VS = "VS";
            TEXT_MATCH = "PARTIDA";
            TEXT_SELECT_TEAM = "SELECIONAR EQUIPA";
            TEXT_MATCHES = "PARTIDAS";
            TEXT_ERR_LS = "	SEU NAVEGADOR DA WEB NÃO É COMPATÍVEL COM ARMAZENAMENTO LOCAL. SE ESTIVER USANDO O SAFARI, ISSO PODE ESTAR RELACIONADO À NAVEGAÇÃO PRIVADA. COMO RESULTADO, ALGUMAS INFORMAÇÕES PODEM NÃO SER SALVAS, OU ALGUNS RECURSOS TALVEZ NÃO ESTEJAM DISPONÍVEIS.";
            TEXT_PLAYER = "JOGADOR";
            TEXT_CPU = "CPU";
            TEXT_EXTRA = "EXTRA";

            TEXT_TEAM [0] = "RÚSSIA";
            TEXT_TEAM [1] = "JAPÃO";
            TEXT_TEAM [2] = "IRÃ";
            TEXT_TEAM [3] = "BRASIL";
            TEXT_TEAM [4] = "MÉXICO";
            TEXT_TEAM [5] = "EUA";
            TEXT_TEAM [6] = "COREIA DO SUL";
            TEXT_TEAM [7] = "ARÁBIA SAUDITA";
            TEXT_TEAM [8] = "ALEMANHA";
            TEXT_TEAM [9] = "INGLATERRA";
            TEXT_TEAM [10] = "ESPANHA";
            TEXT_TEAM [11] = "NIGÉRIA";
            TEXT_TEAM [12] = "COSTA RICA";
            TEXT_TEAM [13] = "POLÔNIA";
            TEXT_TEAM [14] = "EGITO";
            TEXT_TEAM [15] = "SÉRVIA";
            TEXT_TEAM [16] = "CANADÁ";
            TEXT_TEAM [17] = "FRANÇA";
            TEXT_TEAM [18] = "PORTUGAL";
            TEXT_TEAM [19] = "URUGUAI";
            TEXT_TEAM [20] = "ARGENTINA";
            TEXT_TEAM [21] = "COLÔMBIA";
            TEXT_TEAM [22] = "ITÁLIA";
            TEXT_TEAM [23] = "SENEGAL";
            TEXT_TEAM [24] = "MARROCOS";
            TEXT_TEAM [25] = "TUNÍSIA";
            TEXT_TEAM [26] = "SUÍÇA";
            TEXT_TEAM [27] = "CROÁCIA";
            TEXT_TEAM [28] = "SUÉCIA";
            TEXT_TEAM [29] = "DINAMARCA";
            TEXT_TEAM [30] = "AUSTRÁLIA";
            TEXT_TEAM [31] = "PERU";
            TEXT_NETWORK_CONNECTING  = "CONECTANDO...";
            TEXT_WAIT_OPPONENT = "AGUARDANDO ADVERSÁRIO";
            TEXT_OPPONENT_LEFT = "O ADVERSÁRIO SAIU";
            TEXT_PLAYER_DISCONNECTED = "VOCÊ SAIU!";
            TEXT_REMATCH = "Aceita a revanche?";
            TEXT_DISCONNECTED_FROM_SERVER = "DESCONECTOU-SE DO SERVIDOR";
            TEXT_WAITING_FOR_OPPONENT = "AGUARDANDO ADVERSÁRIO";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "OPONENTE QUER JOGAR NOVAMENTE";
            TEXT_NETWORK_OFFLINE = "SEM REDE";
            TEXT_RETURN_TO_HOME = "VOLTAR PARA O INÍCIO";
            TEXT_WRONG_PASSWORD = "Senha incorreta";
            TEXT_ROOM_IS_FULL = "Sala cheia!";
            TEXT_FIND_OPPONENT = "encontrando adversário...";
            TEXT_CONNECT_TO_LOBBY = "Conectar ao lobby...";
            TEXT_MATCH_FOUND = "Partida encontrada!";
            TEXT_ROOM_DOESNT_EXIST = "A sala não existe!";
            TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "esperando oponente entrar no jogo:";

            TEXT_WAIT_STRIKER = "OPONENTE ESTÁ CHUTANDO";
            TEXT_GET_READY = "PREPARE-SE!";
            TEXT_WAIT_GOALKEEPER = "GOLEIRO SE PREPARANDO...";
            TEXT_GET_A_BONUS_SHOT = "QUE TAL UM CHUTE EXTRA?";
            TEXT_PLAYER_WAIT_TO_CALCULATE = "ESPERANDO OPONENTE\nCALCULAR A PONTUAÇÃO";
            TEXT_QUIZ_TIMEOUT = "ACABOU O TEMPO";
            TEXT_WRONG_ANSWER = "ERROU";
            TEXT_CORRECT_ANSWER = "ACERTOU";
            TEXT_BONUS_SHOT = "CHUTE EXTRA";
            TEXT_PLAYER_TURN = "TURNO DE %s";
            TEXT_CPU = "COMPUTADOR";
            TEXT_OPPONENT_BONUS_QUESTION = "PERGUNTA DE CHUTE EXTRA DE OPONENTE";
            TEXT_OPPONENT_WANT_TO_PLAY_AGAIN = "Oponente quer jogar novamente";

            TEXT_XP = "%s / %s XP";
            TEXT_XP_MAX = "MÁX.";
            TEXT_ACHIEVEMENTS = "TROFÉUS";
            TEXT_STATS = "SUAS ESTATÍSTICAS";

            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_BOOT ] = ["Chuteira de bronze","Marque 50 gols"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_BOOT] = ["Chuteira de prata","Marque 250 gols"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_BOOT] = ["Chuteira de ouro","Marque 1.000 gols"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHKICKER] = ["Adoro fazer contas","Acerte 25 questões de matemática"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHOFTHEMATCH] = ["Especialista em matemática","Acerte 100 questões de matemática"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_MATHLEGEND] = ["Calculadora humana","Acerte 500 questões de matemática"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_BRONZE_GLOVE] = ["Luva de bronze","Impeça 25 gols"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_SILVER_GLOVE] = ["Luva de prata","Impeça 100 gols"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOLDEN_GLOVE] = ["Luva de ouro","Impeça 500 gols"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_HAT_TRICK] = ["Pode pedir música","Marque 3 gols em sequência"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_MACHINE] = ["Máquina de gols","Marque 5 ou mais gols em 3 partidas"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_PHENOM] = ["Fenômeno","Marque 5 ou mais gols em 15 partidas"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_GOAL_LEGEND] = ["Lenda futebolística","Marque 5 ou mais gols em 50 partidas"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_THE_FIRST] = ["Primeira vez","Vença a primeira partida"];
            TEXT_LIST_ACHIEVEMENTS [ACHI_WORLD_CHAMPION] = ["Melhor do mundo","Vença o computador na partida 10"];

            TEXT_STATS_LABEL_0 = "Geral";
            TEXT_STATS_LABEL_1 = "Ataque";
            TEXT_STATS_LABEL_2 = "Defesa";
            TEXT_STATS_LABEL_3 = "Precisão matemática";

            TEXT_STATS0_GAMESLABEL = "Jogos";
            TEXT_STATS0_LABELLX = "Venceu";
            TEXT_STATS0_LABELRX = "Perdeu";
            TEXT_STATS0_FAVCOUNTRYLABEL = "País favorito";

            TEXT_STATS1_GOALSCORED = "GOLS MARCADOS";
            TEXT_STATS1_PERFECTGAMES = "JOGOS PERFEITOS";
            TEXT_STATS1_EVERYSHOTS = "Marcou todos os gols";
            TEXT_STATS1_SHOTS_TAKEN = "CHUTOU %s VEZES";
            TEXT_TBD = "EM BREVE";
            TEXT_STATS1_MISSES = "Erros";
            TEXT_STATS1_SAVES = "Defesas";
            TEXT_STATS1_GOALS = "Gols";
            TEXT_PERCENT = "%";
            TEXT_HOT_ZONES = "MELHORES ÁREAS";
            TEXT_NO_SHOTS = "Nenhum chute";
            TEXT_STATS1_HOT_ZONES_DESC = "Os números indicam a porcentagem de gols marcados";
            TEXT_STATS2_SHOTSSAVED = "DEFESAS";
            TEXT_STATS2_SHUTOUTS = "SEM SOFRER GOLS";
            TEXT_STATS2_SAVEPERCENTAGE = "% DE DEFESAS";
            TEXT_STATS2_HOT_ZONES_DESC = "Os números indicam a porcentagem de gols defendidos";
            TEXT_STATS3_ACCURACY = "PRECISÃO";
            TEXT_STATS3_ADDITION = "Adição";
            TEXT_STATS3_SUBTRACTION = "Subtração";
            TEXT_STATS3_MULTIPLICATION = "Multiplicação";
            TEXT_STATS3_DIVISION = "Divisão";
            TEXT_STATS3_TOTAL = "TOTAL";

            TEXT_SUMMARY_TITLE = "EXP GANHA";
            TEXT_SUMMARY_WON = "Vitória";
            TEXT_SUMMARY_LOSS = "Derrota";
            TEXT_SUMMARY_GOALS_SCORED = "Gols marcados";
            TEXT_SUMMARY_GOALS_SAVED = "Gols defendidos";
            TEXT_SUMMARY_SHUTOUT = "Não sofreu gol";
            TEXT_SUMMARY_TROPHIES = "Troféus";
            TEXT_SUMMARY_TOTAL = "Total";
            
            TEXT_SYS_UPDATE ="atualizar";
            TEXT_SYS_CREATEMATCH = "CRIAR PARTIDA";
            TEXT_SYS_OK = "ok";
            TEXT_SYS_BACK = "VOLTAR";
            TEXT_SYS_TYPEROOMPASS = "Digite a senha da sala";
            TEXT_SYS_NAMEROOM = "Nomear sala";
            TEXT_SYS_DEFAULTROOMNAME = "Sala de %s";
            TEXT_SYS_INFOPASS = "Se você não definir uma senha, esta sala será pública.";
            TEXT_SYS_CREATEROOM = "CRIAR SALA";
            TEXT_SYS_CREATE = "criar";
            TEXT_SYS_LOADING = "CARREGANDO...";


            TEXT_SYS_MATCH_LIST = "Entrar em uma partida:";
            TEXT_SYS_QUICKMATCH = "Jogar contra adversário aleatório";
            TEXT_SYS_PASSWORD = "Senha (opcional)";
            TEXT_SYS_PLAY_OFFLINE = "JOGAR OFFLINE";
            TEXT_SYS_NO_CONNECTION = "SEM CONEXÃO<br/>(Conecte-se para encontrar alguém e jogar online)";
            
            
            break;  
        }
    }
}